#! /bin/sh
#
#	rsync-netbsd-cvs - rsync the CVS repo from NetBSD
#
# also updates local working directories....
#
#ident "@(#)LOCAL:rsync-netbsd-cvs,v 1.1 2001/06/06 17:52:06 woods Exp"

PATH=$PATH:/usr/pkg/sbin:/usr/pkg/bin:/usr/local/sbin:/usr/local/bin
export PATH

SITE="rsync.netbsd.org"
METHOD="rsync://"
DIRECTORY="/anoncvs"
EXTERNAL=""

#SITE="rsync.jp.netbsd.org"
#METHOD="rsync://"
#DIRECTORY="/anoncvs"
#EXTERNAL=""

#SITE=""
#METHOD=woods@whome.planix.com:
#DIRECTORY=/u5/NetBSD-CVS/
#EXTERNAL="-e rsh"

LOCKDIR=/tmp/$(basename $0).lock

if [ -e $LOCKDIR ] ; then
	echo "It appears there's already an instance of $0 running..." 1>&2
	exit 1
fi

if mkdir $LOCKDIR ; then
	: #got it!
else
	echo "Oops, just missed grabbing $LOCKDIR!" 1>&2
	exit 1
fi

(
	while true; do
	        printf "START:%s: " "$(date '+%Y/%m/%d-%T')"
		rsync -rlptgoD -vz ${EXTERNAL} --blocking-io --stats --delete --exclude '#cvs.lock' ${METHOD}${SITE}${DIRECTORY} /cvs/master/m-NetBSD/
	        if [ $? -eq 0 ]; then
	                break
	        fi
	        echo ""
		# no newline in case someone's doing a 'tail -f'....
	        printf "PAUSE:%s: " "$(date '+%Y/%m/%d-%T')"
	        sleep 120
	        echo "RESTART"
	done
	echo Done.
) > /var/log/rsync-netbsd-cvs 2>&1

# this produces the Cron report from the raw log...
#
grep -v '/$' /var/log/rsync-netbsd-cvs

WORK_DIRS="/work/NetBSD/doc /work/NetBSD/src /work/NetBSD/xsrc /most/var/httpd/htdocs-netbsd.robohack.ca"

for work_dir in $WORK_DIRS; do
	echo "Updating: $work_dir"
	echo ""
	cd $work_dir; cvs -q update -P -d
	echo ""
done

if [ ! -d $LOCKDIR ] ; then
	echo "OOPS!!!!  $LOCKDIR went missing!!!!" 1>&2
	exit 1
fi
rmdir $LOCKDIR
