#! /bin/sh
#
#	rsync-netbsd-cvs - rsync the CVS repo from NetBSD
#
# also updates local working directories....
#
#ident "@(#)LOCAL:rsync-netbsd-cvs,v 1.55 2006/05/09 15:42:54 woods Exp"

PATH=$PATH:/usr/pkg/sbin:/usr/pkg/bin:/usr/local/sbin:/usr/local/bin
export PATH

#
#	local configuration
#

# uncomment for testing
#
#RSYNC_DEBUG="-vv -n"
#CVS_DEBUG="-n"

# location of the local repository
#
# WARNING: this pathname needs a trailing slash!
#
REPO_DIR="/cvs/master/m-NetBSD/main/"

# NOTE:  If you probably want the following two files in ${REPO_DIR}:
#
# main/CVSROOT/cvsignore:
#	obj
#	obj.*
#	work
#	work.*
#
# main/CVSROOT/config:
#	LockDir=/tmp
#	LogHistory=
#	tag=NetBSD
#
# and you'll want to make them immutable:  'chflags schg'

# places to run "cvs update" after the rsync is done
#
WORK_DIRS="/work/NetBSD/othersrc /work/NetBSD/src /work/NetBSD/src-1.6 /work/NetBSD/xsrc /work/NetBSD/pkgsrc /most/big1/www/htdocs-netbsd.robohack.ca"

# places to run "cvs -n update" after the rsync is done
#
#WORK_DIRS_CHECK="/work/woods/m-NetBSD-pkgsrc"

#
#	remote configuration
#

# master NetBSD site....
#
SITE="anoncvs.netbsd.org"
METHOD="rsync://"
DIRECTORY="/cvsroot/"		# aka the "module", with a trailing slash!
EXTERNAL=""
#
# The "main" sub-directory doesn't exist at anoncvs.netbsd.org, so we
# must include it in the local repo parameter to rsync
#
LOCAL_REPO=${REPO_DIR}

# old site (was another name for the same IP as ftp.netbsd.org):
#
#    "Rsync service for the "anoncvs" module has moved from ftp.netbsd.org to
#    anoncvs.netbsd.org.
#
#    Please see http://mail-index.netbsd.org/netbsd-users/2004/03/29/0010.html
#    for important details."
#
#SITE="rsync.netbsd.org"
#METHOD="rsync://"
#DIRECTORY="/anoncvs/"
#EXTERNAL=""
#
# The "main" sub-directory _does_ exist at rsync.netbsd.org...
#
#LOCAL_REPO=${REPO_DIR%%main/}

# alternate site
#
#SITE="rsync.jp.netbsd.org"
#METHOD="rsync://"
#DIRECTORY="/anoncvs/"
#
# Does the "main" sub-directory exist at rsync.jp.netbsd.org?
#
#LOCAL_REPO=${REPO_DIR}
#EXTERNAL=""

# alternate site showing use of rsh
#
#SITE=""
#METHOD="woods@whome.planix.com:"
#DIRECTORY="/u5/NetBSD-CVS/"		# XXX not sure this is right any more
#LOCAL_REPO=${REPO_DIR}
#EXTERNAL="-e rsh --blocking-io"

# WARNING:  this script could fail to interlock properly if it can be
# invoked simultaneously with more than one name!  Don't do that!
# 
LOCKDIR=/tmp/$(basename $0).lock

if [ -e $LOCKDIR ] ; then
	echo "It appears there's already an instance of $0 running..." 1>&2
	exit 1
fi

if mkdir $LOCKDIR ; then
	: #got it!
else
	echo "Oops, just missed grabbing $LOCKDIR!" 1>&2
	exit 1
fi

cp /var/log/rsync-netbsd-cvs /var/log/rsync-netbsd-cvs.old

(
	while true; do
	        printf "START:%s: rsync\n" "$(date '+%Y/%m/%d-%T')"
		rsync ${DEBUG} -rlptHS -vz ${EXTERNAL} --stats --delete --delete-after --exclude '#cvs.lock' ${METHOD}${SITE}${DIRECTORY} ${LOCAL_REPO}
		rc=$?
		#
		# Note that E#23 happens normally when rsync can't
		# delete the files I've made purposefully immutable
		# specifically so that it can't delete them.
		#
		# Also presumably if the remote server had a problem
		# or there was some other filesystem error on this end
		# then we should just give up and report what happened
		# and wait for tomorrow to try again
		#
	        if [ $rc -eq 0 -o $rc -eq 23 ]; then
	                break
		else
			echo ""
			printf "FAILED:%s: rsync exited with code: %d\n" "$(date '+%Y/%m/%d-%T')" $rc
	        fi
		# no newline in case someone's doing a 'tail -f'....
	        printf "PAUSE:%s: " "$(date '+%Y/%m/%d-%T')"
	        sleep 60
	        echo "RESTART"
	done
        printf "DONE:%s: rsync\n" "$(date '+%Y/%m/%d-%T')"
) > /var/log/rsync-netbsd-cvs 2>&1

# this produces the Cron report from the raw log by ignoring any line
# which ends in a '/' (presumably it's just one of the directories
# that was updated)
#
grep -v '/$' /var/log/rsync-netbsd-cvs
echo ""

# re-create directories in the REPO that we have local but of course
# uncommitted new files within...
#
# we could make these immutable but since they are directories that
# might just cause more problems than it solves...
#
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/benchmarks/postal/patches"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/databases/rrdtool-nodep"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/databases/rrdtool-nodep/patches"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/devel/tre/patches"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/mail/cyrus-imapd21-cyradm"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/mail/smail"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/mail/smail/files"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/mail/smail/scripts"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/mail/smail+cyrus"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/mail/smail+cyrus+whoson"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/mail/smail+whoson"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/mail/smtprc"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/mail/smtprc/patches"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/mail/vrfy"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/mail/vrfy/patches"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/net/eping"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/net/eping/patches"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/net/whoson/patches"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/pkgtools/mailwrapper"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/pkgtools/mailwrapper/files"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/sysutils/pwgen/patches"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/www/apache+modssl-local"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/www/apache+modssl-local/files"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/www/apache+modssl-local/patches"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/x11/xcb/patches"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/pkgsrc/x11/xterm/patches"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/bin/awk"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/bin/fgrep"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/bin/nc"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/dist/dhcp/contrib/ms2isc"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/dist/dhcp/doc/ja_JP.eucJP"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/etc/namedb/master"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/lib/libcrack"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/libexec/fingerd/samples"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/libexec/pkcrackdict"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/libexec/sccs"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/libexec/sccs/cmd"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/libexec/sccs/com"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/libexec/sccs/doc"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/libexec/sccs/hdr"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/libexec/sccs/help.d"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/libexec/sccs/util"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/libexec/unpkcrackdict"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/regress/usr.sbin"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/regress/usr.sbin/pwd_mkdb"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/usr.bin/grep"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/usr.bin/host"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/usr.bin/sccs"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/usr.bin/sccs/PSD.doc"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/usr.bin/testpasswd"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/usr.bin/vacation/librfc2822"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/usr.bin/xd"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/usr.sbin/flc"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/usr.sbin/flc/BNF"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/usr.sbin/idecrypt"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/usr.sbin/lmhw"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/usr.sbin/mkcrackdict"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/usr.sbin/update-protocols"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/tools/mkcrackdict"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/tools/newsyslog"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/src/tools/pkcrackdict"
LOCAL_MKDIRS="${LOCAL_MKDIRS} ${REPO_DIR}/xsrc/xc/programs/xterm/X11"

install -d -m 775 ${LOCAL_MKDIRS}


for work_dir in $WORK_DIRS; do
	echo "================================================================"
        printf "\nSTART:%s: cvs update $work_dir\n\n" "$(date '+%Y/%m/%d-%T')"
	cd $work_dir && cvs ${CVS_DEBUG} -u -q update -P -d
        printf "\nDONE:%s: updating $work_dir\n\n" "$(date '+%Y/%m/%d-%T')"
	if [ -x /usr/pkg/bin/lintpkgsrc -a -f $work_dir/packages-to-upgrade -a $(basename $work_dir) = "pkgsrc" ] ; then
		/usr/pkg/bin/lintpkgsrc -P $work_dir -i | tee $work_dir/packages-to-upgrade.new
		if [ -s $work_dir/packages-to-upgrade.new ] ; then
			mv -f $work_dir/packages-to-upgrade.new  $work_dir/packages-to-upgrade
		fi
	fi
done

for work_dir in $WORK_DIRS_CHECK; do
        printf "\nSTART:%s: cvs -n update $work_dir\n\n" "$(date '+%Y/%m/%d-%T')"
	cd $work_dir && cvs -u -nq update -P -d 2>&1 | fgrep -v 'cvs update: New directory'
        printf "\nDONE:%s: checking $work_dir\n\n" "$(date '+%Y/%m/%d-%T')"
done

if [ ! -d $LOCKDIR ] ; then
	echo "OOPS!!!!  $LOCKDIR went missing!!!!" 1>&2
	exit 1
fi
rmdir $LOCKDIR

exit $?
